#!/usr/bin/env bash
# Display listening TCP/UDP ports and UNIX domain sockets with PID/program name

# Run: sudo ./4-TCP_and_UDP_ports

# Internet (TCP/UDP) - listening only + PID/program name
netstat -lntpu

# UNIX domain sockets - listening only + PID/program name
netstat -lxp
